name: 'bastion infra project'


trigger : none

pool: 
  name: infra_agentpool

variables:
  WORK_DIR: '$(System.DefaultWorkingDirectory)/environments/dev'
  SERVICE_CONNECTION: 'infra-azure-connection'


stages:
 - stage: initvalidateplan
   displayName: terraform init/validate/plan
   jobs:
     - job: jobinitvalidateplan
       steps:

       - task: TerraformInstaller@1
         displayName: terraform install
         inputs:
           terraformVersion: 'latest'

       - task: TerraformTask@5
         displayName: terraform init
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: '$(WORK_DIR)'
           backendServiceArm: '$(SERVICE_CONNECTION)'
           backendAzureRmOverrideSubscriptionID: '8b10287d-12d6-41e3-b62c-33457c006e96'
           backendAzureRmResourceGroupName: 'bappa-remotestate-rg'
           backendAzureRmStorageAccountName: 'bappastatefiles'
           backendAzureRmContainerName: 'statecfiles'
           backendAzureRmKey: 'bastiondev.tfstate'

       - task: TerraformTask@5
         displayName: terraform validate
         inputs:
           provider: 'azurerm'
           command: 'validate'
           workingDirectory: '$(WORK_DIR)'

       - task: TerraformTask@5
         displayName: terraform plan
         inputs:
           provider: 'azurerm'
           command: 'plan'
           workingDirectory: '$(WORK_DIR)'
           environmentServiceNameAzureRM: '$(SERVICE_CONNECTION)'

 - stage: codescanning
   displayName: tfscan
   jobs:
     - job: tfsecscanning
       steps:
       - task: tfsec@1
         continueOnError: true
         inputs:
           version: 'v1.26.0'
           dir: '$(WORK_DIR)'

 - stage: apply
   dependsOn: codescanning
   displayName: manual approval
   jobs:
     - job: manualvalidation
       pool: server
       steps:
       - task: ManualValidation@1
         displayName: manual validation by manager
         inputs:
           notifyUsers: 'bappakn22@gmail.com'
           approvers: 'bappakn22@gmail.com'
           instructions: 'please approve'
          


     - job: terraformapply
       dependsOn: manualvalidation
       pool:
        vmImage: ubuntu-latest 
       condition: succeeded ()


       steps:
       - task: TerraformInstaller@1
         displayName: terraform install
         inputs:
           terraformVersion: 'latest'

       - task: TerraformTask@5
         displayName: terraform init
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: '$(WORK_DIR)'
           backendServiceArm: '$(SERVICE_CONNECTION)'
           backendAzureRmOverrideSubscriptionID: '8b10287d-12d6-41e3-b62c-33457c006e96'
           backendAzureRmResourceGroupName: 'bappa-remotestate-rg'
           backendAzureRmStorageAccountName: 'bappastatefiles'
           backendAzureRmContainerName: 'statecfiles'
           backendAzureRmKey: 'bastiondev.tfstate'

       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'apply'
           workingDirectory: '$(WORK_DIR)'
           commandOptions: '--auto-approve'
           environmentServiceNameAzureRM: '$(SERVICE_CONNECTION)'
      
   